---
- name: Install apache and upload webpage
  hosts: all
  become: yes


  vars:
    source_file: ~/ansible/playbook_files/index.html
    destin_file: /var/www/html


  tasks:
 
  - name: Check and print os family
    debug: var=ansible_os_family
  
  - block: #=============FOR REDHAT==============#
 
      - name: install apache webserver for RedHat OS's
        yum: name=httpd state=latest

      - name: Copy mypage to servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart apache RedHat

      - name: start webserver and make it enable for RedHat
        service: name=httpd state=started enabled=yes
   
    when: ansible_os_family == "RedHat"

  - block: #==========FOR UBUNTU===============#

      - name: Apache webserver for Debian OS's
        apt: name=apache2 state=latest

      - name: Copy mypage to servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart apache Debian
      
      - name: Start webserver service for Debian
        service: name=apache2 state=started enabled=yes
  
    when: ansible_os_family == "Debian"

  handlers:
    - name: Restart apache RedHat
      service: name=httpd state=restarted
    - name: Restart apache Debian
      service: name=apache2 state=restarted
