---
- name: Install httpd
  hosts: all
  become: true

  tasks:
    - name: Install apache web-server
      yum:
        name: httpd
        state: latest


    - name: Start apache and enable on boot
      service:
        name: httpd
        state: started
        enabled: true
